package com.example.podclassic.media

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.exp
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sqrt
import kotlin.math.tanh

/**
 * Sample-rate aware, stereo-linked tube colour processor.
 *
 * The non-linear stage uses two-times oversampling, an asymmetric transfer curve and a DC
 * blocker.  The tone section is shelving rather than the destructive low-pass used by the old
 * implementation.  This class contains no Android dependencies so its behaviour can be tested.
 */
class TubeAmpDsp {
    data class Parameters(
        val enabled: Boolean = false,
        val drive: Float = 1.25f,
        val saturation: Float = 0.30f,
        val harmonics: Float = 0.18f,
        val compressionRatio: Float = 1.2f,
        val attackMs: Float = 25f,
        val releaseMs: Float = 220f,
        val warmth: Float = 0.40f
    )

    @Volatile
    var parameters = Parameters()

    private var sampleRate = 44_100f
    private var channels = 2
    private var previousInput = FloatArray(channels)
    private var dcInput = FloatArray(channels)
    private var dcOutput = FloatArray(channels)
    private var lowState = FloatArray(channels)
    private var highLowState = FloatArray(channels)
    private var envelope = 0f
    private var compressorGain = 1f

    fun configure(sampleRate: Int, channelCount: Int) {
        this.sampleRate = sampleRate.coerceAtLeast(8_000).toFloat()
        channels = channelCount.coerceAtLeast(1)
        previousInput = FloatArray(channels)
        dcInput = FloatArray(channels)
        dcOutput = FloatArray(channels)
        lowState = FloatArray(channels)
        highLowState = FloatArray(channels)
        reset()
    }

    fun reset() {
        previousInput.fill(0f)
        dcInput.fill(0f)
        dcOutput.fill(0f)
        lowState.fill(0f)
        highLowState.fill(0f)
        envelope = 0f
        compressorGain = 1f
    }

    /** Processes one interleaved frame in place and returns it for convenient streaming use. */
    fun processFrame(frame: FloatArray): FloatArray {
        val p = parameters
        if (!p.enabled) return frame

        var detector = 0f
        for (channel in frame.indices) detector += frame[channel] * frame[channel]
        detector = sqrt(detector / frame.size.coerceAtLeast(1))

        val attack = timeCoefficient(p.attackMs)
        val release = timeCoefficient(p.releaseMs)
        envelope += (detector - envelope) * if (detector > envelope) attack else release

        val threshold = dbToLinear(-9f)
        val ratio = p.compressionRatio.coerceIn(1f, 2f)
        val targetGain = if (envelope > threshold) {
            val compressed = threshold * (envelope / threshold).toDouble().pow(1.0 / ratio).toFloat()
            compressed / envelope
        } else {
            1f
        }
        compressorGain += (targetGain - compressorGain) *
            if (targetGain < compressorGain) attack else release

        val channelLimit = min(frame.size, channels)
        for (channel in 0 until channelLimit) {
            val dry = frame[channel].coerceIn(-1f, 1f)
            // Two-times oversampling by processing the interpolated midpoint and current sample.
            val midpoint = (previousInput[channel] + dry) * 0.5f
            val wet = (shape(midpoint, p) + shape(dry, p)) * 0.5f
            previousInput[channel] = dry

            val mix = (0.08f + p.saturation.coerceIn(0f, 1f) * 0.30f)
            var value = dry * (1f - mix) + wet * mix

            // Remove the DC generated by the deliberately asymmetric triode transfer curve.
            val dcBlocked = value - dcInput[channel] + 0.995f * dcOutput[channel]
            dcInput[channel] = value
            dcOutput[channel] = dcBlocked
            value = dcBlocked * compressorGain

            // Gentle low/high shelves: about +1.2 dB at 180 Hz and -1 dB above 8 kHz at max.
            val lowAlpha = onePoleAlpha(180f)
            lowState[channel] += lowAlpha * (value - lowState[channel])
            val lowAmount = dbToLinear(1.2f * p.warmth.coerceIn(0f, 1f)) - 1f

            val highAlpha = onePoleAlpha(8_000f)
            highLowState[channel] += highAlpha * (value - highLowState[channel])
            val high = value - highLowState[channel]
            val highAmount = dbToLinear(-1.0f * p.warmth.coerceIn(0f, 1f)) - 1f

            value += lowState[channel] * lowAmount + high * highAmount
            frame[channel] = value.coerceIn(-OUTPUT_CEILING, OUTPUT_CEILING)
        }
        return frame
    }

    private fun shape(sample: Float, p: Parameters): Float {
        val drive = p.drive.coerceIn(1f, 2.2f)
        val bias = p.harmonics.coerceIn(0f, 1f) * 0.16f
        val driven = sample * (0.82f + 0.18f * drive)
        val zero = tanh(drive * bias)
        val normalizer = max(
            abs(tanh(drive * (1f + bias)) - zero),
            abs(tanh(drive * (-1f + bias)) - zero)
        ).coerceAtLeast(0.001f)
        return ((tanh(drive * (driven + bias)) - zero) / normalizer).coerceIn(-1.2f, 1.2f)
    }

    private fun onePoleAlpha(frequency: Float): Float =
        (1f - exp((-2.0 * PI * frequency / sampleRate).toFloat())).coerceIn(0f, 1f)

    private fun timeCoefficient(timeMs: Float): Float {
        val seconds = timeMs.coerceAtLeast(1f) / 1000f
        return 1f - exp(-1f / (seconds * sampleRate))
    }

    private fun dbToLinear(db: Float): Float = 10.0.pow(db / 20.0).toFloat()

    companion object {
        const val OUTPUT_CEILING = 0.8912509f // -1 dBFS
    }
}
